### ISSUE TITLE
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:npm (npm install) on project atlas-dashboardv2: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

### ISSUE THREAD

**Issue by vettrivikas** [lucasmsp/docker-atlas#1]
[INFO] Apache Atlas Server Build Tools 1.0 ................ SUCCESS [  5.478 s]
[INFO] apache-atlas 3.0.0-SNAPSHOT ........................ SUCCESS [ 16.236 s]
[INFO] Apache Atlas Test Utility Tools .................... SUCCESS [ 32.468 s]
[INFO] Apache Atlas Integration ........................... SUCCESS [ 10.953 s]
[INFO] Apache Atlas Common ................................ SUCCESS [  2.485 s]
[INFO] Apache Atlas Client ................................ SUCCESS [  0.341 s]
[INFO] atlas-client-common ................................ SUCCESS [  1.190 s]
[INFO] atlas-client-v1 .................................... SUCCESS [  1.318 s]
[INFO] Apache Atlas Server API ............................ SUCCESS [  1.041 s]
[INFO] Apache Atlas Notification .......................... SUCCESS [  6.789 s]
[INFO] atlas-client-v2 .................................... SUCCESS [  1.223 s]
[INFO] Apache Atlas Graph Database Projects ............... SUCCESS [  0.120 s]
[INFO] Apache Atlas Graph Database API .................... SUCCESS [  2.156 s]
[INFO] Graph Database Common Code ......................... SUCCESS [  1.646 s]
[INFO] Apache Atlas JanusGraph-HBase2 Module .............. SUCCESS [  9.495 s]
[INFO] Apache Atlas JanusGraph DB Impl .................... SUCCESS [ 18.867 s]
[INFO] Apache Atlas Graph Database Implementation Dependencies SUCCESS [  2.450 s]
[INFO] Apache Atlas Authorization ......................... SUCCESS [  1.481 s]
[INFO] Apache Atlas Repository ............................ SUCCESS [ 28.864 s]
[INFO] Apache Atlas UI .................................... FAILURE [ 17.731 s]
[INFO] Apache Atlas New UI ................................ SKIPPED
[INFO] Apache Atlas Web Application ....................... SKIPPED
[INFO] Apache Atlas Documentation ......................... SKIPPED
[INFO] Apache Atlas FileSystem Model ...................... SKIPPED
[INFO] Apache Atlas Plugin Classloader .................... SKIPPED
[INFO] Apache Atlas Hive Bridge Shim ...................... SKIPPED
[INFO] Apache Atlas Hive Bridge ........................... SKIPPED
[INFO] Apache Atlas Falcon Bridge Shim .................... SKIPPED
[INFO] Apache Atlas Falcon Bridge ......................... SKIPPED
[INFO] Apache Atlas Sqoop Bridge Shim ..................... SKIPPED
[INFO] Apache Atlas Sqoop Bridge .......................... SKIPPED
[INFO] Apache Atlas Storm Bridge Shim ..................... SKIPPED
[INFO] Apache Atlas Storm Bridge .......................... SKIPPED
[INFO] Apache Atlas Hbase Bridge Shim ..................... SKIPPED
[INFO] Apache Atlas Hbase Bridge .......................... SKIPPED
[INFO] Apache HBase - Testing Util ........................ SKIPPED
[INFO] Apache Atlas Kafka Bridge .......................... SKIPPED
[INFO] Apache Atlas classification updater ................ SKIPPED
[INFO] Apache Atlas Impala Hook API ....................... SKIPPED
[INFO] Apache Atlas Impala Bridge Shim .................... SKIPPED
[INFO] Apache Atlas Impala Bridge ......................... SKIPPED
[INFO] Apache Atlas Distribution 3.0.0-SNAPSHOT ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2022-03-25T10:04:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:npm (npm install) on project atlas-dashboardv2: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :atlas-dashboardv2
ERROR: Service 'atlas-server' failed to build: The command '/bin/sh -c git clone http://github.com/apache/atlas.git     && cd atlas && git reset --hard $ATLAS_REV  && mvn clean -DskipTests package -Pdist,embedded-hbase-solr     && mv distro/target/apache-atlas-*-bin.tar.gz /apache-atlas.tar.gz' returned a non-zero code: 1

**Comment by lucasmsp** [comment]
Hi @vettrivikas, how are you doing ? Are you trying to compile outside Docker? Anyway, the problem can be a misconfiguration of $ATLAS_REV. If you compile atlas using the right commit (21b15842fd74bc91910b2d8901dbea57769065d0) it will be ok. In general, the current master branch is used in the development and could present errors, if you want a recent version, try to use a stable version. Also, this error could also be related to a network error while trying to download some dependency. 

I followed the same steps and this solution continues to work today.

**Comment by vettrivikas** [comment]
Yes right, Due to npm,
![image](https://user-images.githubusercontent.com/32515723/160540833-add99ac4-4aac-47c3-8740-662acc48deac.png)

**Comment by vettrivikas** [comment]
Please help to solve this

**Comment by lucasmsp** [comment]
Hi, the error 404 is because the Node-SASS URL was removed. Try to replace it to `https://github.com/sass/node-sass/releases/download/v4.13.1/linux-x64-72_binding.node`

**Comment by lucasmsp** [comment]
Hi @vettrivikas, I'm closing this issue... I'm hoping that you managed to compile it.

**Comment by daraul** [comment]
> If you compile atlas using the right commit (21b15842fd74bc91910b2d8901dbea57769065d0) it will be ok

@lucasmsp [that commit](https://github.com/lucasmsp/docker-atlas/commit/21b15842fd74bc91910b2d8901dbea57769065d0) doesn't exist. Is there another that I can try?

edit: I now realize that that commit wasn't for this project, but for a (not seemingly nonexistent) variable named ATLAS_REV, from the atlas Dockerfile. I'm experiencing the issue that's described at the top here, but I don't know how I'd resolve it. I just ran `docker-compose build` in the project's root directory.
