### ISSUE TITLE
Runtime error because python not found

### ISSUE THREAD

**Issue by robryb** [lucasmsp/docker-atlas#11]
I am working my way through the tutorial in README.md on a Windows 10 computer. I am running the tutorial from WSL2. I hit a python error at the following step:

` # /usr/local/spark/bin/spark-submit /tmp/teste.py `
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/spark/jars/spark-atlas-connector-assembly-0.1.0-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/spark/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
23/05/23 14:51:45 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
**Exception in thread "main" java.io.IOException: Cannot run program "python": error=2, No such file or directory**
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:100)

Rest of stack dump removed.

I created a symbolic link in the spark container from python to python3 and the python issue was resolved.

` # ln  -s  /usr/bin/python  /usr/bin/python3 `

**Comment by lucasmsp** [comment]
This error is fixed in #14
