### ISSUE TITLE
Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 could not be resolved

### ISSUE THREAD

**Issue by anassbouchfar** [lucasmsp/docker-atlas#12]
#0 1645.7 [ERROR] Plugin org.apache.maven.plugins:maven-antrun-plugin:1.7 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-antrun-plugin:jar:1.7: Could not transfer artifact org.apache.maven.plugins:maven-antrun-plugin:pom:1.7 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]

failed to solve: executor failed running [/bin/sh -c git clone http://github.com/apache/atlas.git 	&& cd atlas 	&& git reset --hard $ATLAS_REV 	&& mvn clean -DskipTests package -Pdist,embedded-hbase-solr 	&& mv distro/target/apache-atlas-*-bin.tar.gz /apache-atlas.tar.gz]: exit code: 1

**Comment by lucasmsp** [comment]
Fixed in #14
