### ISSUE TITLE
Can't run spark

### ISSUE THREAD

**Issue by ZSLajevardi** [lucasmsp/docker-atlas#2]
Hi
I've been trying to install apache atlas on ubuntu 20.04 (local) using this docker image, but it has been stuck on step 12 while running spark.

![Screenshot (82)](https://user-images.githubusercontent.com/73718705/163541496-8d74845d-a1b4-44b1-b259-c4c9c2226cc0.png)

Any ideas what went wrong here?

**Comment by lucasmsp** [comment]
Hi, Could you provide more information? Did you change any variable in Dockerfile like SPARK_VERSION or HADOOP_VERSION ? Probably this error is due to `tar` was not able to extract the spark tgz file, probably by a problem in curl like an unavailable link or any other network problem. If you did not change Spark version, the Dockerfile will try to download spark at `https://downloads.apache.org/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz`. You are able to download it manually?

**Comment by ZSLajevardi** [comment]
Hey there,
Thanks for your responding.
I did not change anything and I just simply run 'docker compose up' after cloning the repository and after pulling wurstmeister/kafka , wbaa/rokku-dev-apache-atlas, bde2020/hive-metastore-postgresql, wurstmeister/zookeeper, maven, bde2020/hadoop-datanode , bde2020/hadoop-namenode and bde2020/hive; I have the following results:

![Screenshot (86)](https://user-images.githubusercontent.com/73718705/163564339-c193a704-bd58-45dd-9e45-9e9e44ab4571.png)

![Screenshot (87)](https://user-images.githubusercontent.com/73718705/163564293-987ae9d4-77d5-4aa4-8fae-cb3b0c441b09.png)

And in the end, yes I can download spark manually from https://downloads.apache.org/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz but it took about 15-20 minutes to download.

**Comment by lucasmsp** [comment]
Hi, I guess it is a bug in your network or your docker version. If you want to debug further, try to download spark using this link in a created ubuntu container. If is bug in docker, trying to compile the following `cd spark; docker build --network=host -t lucasmsp/spark:2.4 .` could help (by using the host network, Docker's DNS problems are avoided). 

Anyway, I just update this repository to use a more recent Ubuntu image. In addition, I update docker-compose file to use an already compiled image (docker pull lucasmsp/spark:2.4). I hope this helps you.

**Comment by ZSLajevardi** [comment]
Hi @lucasmsp 
I used the updated repository and the spark error is resolved. but after I received the 'Apache Atlas server Started' massage, I've got 503 error as following:


ocker-atlas-atlas-server-1               | ...............................................................................
docker-atlas-atlas-server-1               | Apache Atlas Server started!!!
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | Creating  ingestion-source type... 
docker-atlas-atlas-server-1               |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
docker-atlas-atlas-server-1               |                                  Dload  Upload   Total   Spent    Left  Speed
 23  1529  100   354    0     0   1076      0HTTP/1.1 503 Service Unavailable0
docker-atlas-atlas-server-1               | Date: Sat, 16 Apr 2022 04:23:04 GMT
docker-atlas-atlas-server-1               | Cache-Control: must-revalidate,no-cache,no-store
docker-atlas-atlas-server-1               | Content-Type: text/html;charset=iso-8859-1
docker-atlas-atlas-server-1               | Content-Length: 354
docker-atlas-atlas-server-1               | Connection: close
docker-atlas-atlas-server-1               | Server: Jetty(9.3.14.v20161028)
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | <html>
docker-atlas-atlas-server-1               | <head>
docker-atlas-atlas-server-1               | <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
docker-atlas-atlas-server-1               | <title>Error 503 </title>
docker-atlas-atlas-server-1               | </head>
docker-atlas-atlas-server-1               | <body>
docker-atlas-atlas-server-1               | <h2>HTTP ERROR: 503</h2>
docker-atlas-atlas-server-1               | <p>Problem accessing /api/atlas/v2/types/typedefs. Reason:
docker-atlas-atlas-server-1               | <pre>    Service Unavailable</pre></p>
docker-atlas-atlas-server-1               | <hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>
docker-atlas-atlas-server-1               | </body>
docker-atlas-atlas-server-1               | </html>
docker-atlas-atlas-server-1               |  --:--:-- --:--:-- --:--:--  1079
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | ingestion-source created
docker-atlas-atlas-server-1               | Creating file type... 
docker-atlas-atlas-server-1               |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
docker-atlas-atlas-server-1               |                                  Dload  Upload   Total   Spent    Left  Speed
100  1012  100   354  100   658  12936  24045 --:--:-- --:--:-- --:--:-- 24370
docker-atlas-atlas-server-1               | HTTP/1.1 503 Service Unavailable
docker-atlas-atlas-server-1               | Date: Sat, 16 Apr 2022 04:23:04 GMT
docker-atlas-atlas-server-1               | Cache-Control: must-revalidate,no-cache,no-store
docker-atlas-atlas-server-1               | Content-Type: text/html;charset=iso-8859-1
docker-atlas-atlas-server-1               | Content-Length: 354
docker-atlas-atlas-server-1               | Server: Jetty(9.3.14.v20161028)
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | <html>
docker-atlas-atlas-server-1               | <head>
docker-atlas-atlas-server-1               | <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
docker-atlas-atlas-server-1               | <title>Error 503 </title>
docker-atlas-atlas-server-1               | </head>
docker-atlas-atlas-server-1               | <body>
docker-atlas-atlas-server-1               | <h2>HTTP ERROR: 503</h2>
docker-atlas-atlas-server-1               | <p>Problem accessing /api/atlas/v2/types/typedefs. Reason:
docker-atlas-atlas-server-1               | <pre>    Service Unavailable</pre></p>
docker-atlas-atlas-server-1               | <hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>
docker-atlas-atlas-server-1               | </body>
docker-atlas-atlas-server-1               | </html>
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | classifications type created
docker-atlas-atlas-server-1               | Creating  rokku_client type... 
docker-atlas-atlas-server-1               |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
docker-atlas-atlas-server-1               |                                  Dload  Upload   Total   Spent    Left  Speed
 20  HTTP/1.1 503 Service Unavailable0      0 --:--:-- --:--:-- --:--:--     0
docker-atlas-atlas-server-1               | Date: Sat, 16 Apr 2022 04:23:04 GMT
docker-atlas-atlas-server-1               | Cache-Control: must-revalidate,no-cache,no-store
docker-atlas-atlas-server-1               | Content-Type: text/html;charset=iso-8859-1
docker-atlas-atlas-server-1               | Content-Length: 354
docker-atlas-atlas-server-1               | Connection: close
docker-atlas-atlas-server-1               | Server: Jetty(9.3.14.v20161028)
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | <html>
docker-atlas-atlas-server-1               | <head>
docker-atlas-atlas-server-1               | <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
docker-atlas-atlas-server-1               | <title>Error 503 </title>
docker-atlas-atlas-server-1               | </head>
docker-atlas-atlas-server-1               | <body>
docker-atlas-atlas-server-1               | <h2>HTTP ERROR: 503</h2>
docker-atlas-atlas-server-1               | <p>Problem accessing /api/atlas/v2/types/typedefs. Reason:
docker-atlas-atlas-server-1               | <pre>    Service Unavailable</pre></p>
docker-atlas-atlas-server-1               | <hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.14.v20161028</a><hr/>
docker-atlas-atlas-server-1               | </body>
docker-atlas-atlas-server-1               | </html>
docker-atlas-atlas-server-1               | 
docker-atlas-atlas-server-1               | rokku_client created
docker-atlas-atlas-server-1               | 1687  100   354    0     0  16833      0 --:--:-- --:--:-- --:--:-- 17700
docker-atlas-atlas-server-1               | Done setting up Atlas types 


I can manually access 'http://eclipse.org/jetty' but It got stuck here and the process won't end unless I gracefully cancel it.

**Comment by lucasmsp** [comment]
Hi, starting Atlas and others containers (hive, spark, etc) at the same time could take some time depending on your machine. Although the errors, I can see through this log that atlas is progressing. Try to start only atlas and its dependencies first (`docker-compose up atlas-server zookeeper kafka`). The first start will take a longer time because it needs to download and prepare the environment.
