### ISSUE TITLE
Atlas Hive bridge error

### ISSUE THREAD

**Issue by davidpr** [lucasmsp/docker-atlas#3]
When doing a docker-compose build I get the following error: (I commented the spark service in the yaml file to avoid spark errors that appeared before)

#0 559.0 [INFO] ------------------------------------------------------------------------
#0 559.0 [INFO] Reactor Summary:
#0 559.0 [INFO] 
#0 559.0 [INFO] Apache Atlas Server Build Tools 1.0 ................ SUCCESS [ 10.668 s]
#0 559.0 [INFO] apache-atlas 3.0.0-SNAPSHOT ........................ SUCCESS [ 34.425 s]
#0 559.0 [INFO] Apache Atlas Test Utility Tools .................... SUCCESS [01:00 min]
#0 559.0 [INFO] Apache Atlas Integration ........................... SUCCESS [ 11.711 s]
#0 559.0 [INFO] Apache Atlas Common ................................ SUCCESS [  3.447 s]
#0 559.0 [INFO] Apache Atlas Client ................................ SUCCESS [  0.562 s]
#0 559.0 [INFO] atlas-client-common ................................ SUCCESS [  0.910 s]
#0 559.0 [INFO] atlas-client-v1 .................................... SUCCESS [  0.816 s]
#0 559.0 [INFO] Apache Atlas Server API ............................ SUCCESS [  0.863 s]
#0 559.0 [INFO] Apache Atlas Notification .......................... SUCCESS [ 10.956 s]
#0 559.0 [INFO] atlas-client-v2 .................................... SUCCESS [  0.693 s]
#0 559.0 [INFO] Apache Atlas Graph Database Projects ............... SUCCESS [  0.069 s]
#0 559.0 [INFO] Apache Atlas Graph Database API .................... SUCCESS [  3.564 s]
#0 559.0 [INFO] Graph Database Common Code ......................... SUCCESS [  1.256 s]
#0 559.0 [INFO] Apache Atlas JanusGraph-HBase2 Module .............. SUCCESS [ 15.263 s]
#0 559.0 [INFO] Apache Atlas JanusGraph DB Impl .................... SUCCESS [ 31.988 s]
#0 559.0 [INFO] Apache Atlas Graph Database Implementation Dependencies SUCCESS [  1.842 s]
#0 559.0 [INFO] Apache Atlas Authorization ......................... SUCCESS [  1.429 s]
#0 559.0 [INFO] Apache Atlas Repository ............................ SUCCESS [ 39.991 s]
#0 559.0 [INFO] Apache Atlas UI .................................... SUCCESS [ 55.134 s]
#0 559.0 [INFO] Apache Atlas New UI ................................ SUCCESS [ 50.563 s]
#0 559.0 [INFO] Apache Atlas Web Application ....................... SUCCESS [02:09 min]
#0 559.0 [INFO] Apache Atlas Documentation ......................... SUCCESS [  1.872 s]
#0 559.0 [INFO] Apache Atlas FileSystem Model ...................... SUCCESS [  3.860 s]
#0 559.0 [INFO] Apache Atlas Plugin Classloader .................... SUCCESS [  0.517 s]
#0 559.0 [INFO] Apache Atlas Hive Bridge Shim ...................... SUCCESS [ 27.236 s]
#0 559.0 [INFO] Apache Atlas Hive Bridge ........................... FAILURE [ 27.176 s]
#0 559.0 [INFO] Apache Atlas Falcon Bridge Shim .................... SKIPPED
#0 559.0 [INFO] Apache Atlas Falcon Bridge ......................... SKIPPED
#0 559.0 [INFO] Apache Atlas Sqoop Bridge Shim ..................... SKIPPED
#0 559.0 [INFO] Apache Atlas Sqoop Bridge .......................... SKIPPED
#0 559.0 [INFO] Apache Atlas Storm Bridge Shim ..................... SKIPPED
#0 559.0 [INFO] Apache Atlas Storm Bridge .......................... SKIPPED
#0 559.0 [INFO] Apache Atlas Hbase Bridge Shim ..................... SKIPPED
#0 559.0 [INFO] Apache Atlas Hbase Bridge .......................... SKIPPED
#0 559.0 [INFO] Apache HBase - Testing Util ........................ SKIPPED
#0 559.0 [INFO] Apache Atlas Kafka Bridge .......................... SKIPPED
#0 559.0 [INFO] Apache Atlas classification updater ................ SKIPPED
#0 559.0 [INFO] Apache Atlas Impala Hook API ....................... SKIPPED
#0 559.0 [INFO] Apache Atlas Impala Bridge Shim .................... SKIPPED
#0 559.0 [INFO] Apache Atlas Impala Bridge ......................... SKIPPED
#0 559.0 [INFO] Apache Atlas Distribution 3.0.0-SNAPSHOT ........... SKIPPED
#0 559.0 [INFO] ------------------------------------------------------------------------
#0 559.0 [INFO] BUILD FAILURE
#0 559.0 [INFO] ------------------------------------------------------------------------
#0 559.0 [INFO] Total time: 08:59 min
#0 559.0 [INFO] Finished at: 2022-12-06T19:57:35Z
#0 559.0 [INFO] ------------------------------------------------------------------------
#0 559.0 [ERROR] Failed to execute goal on project hive-bridge: Could not resolve dependencies for project org.apache.atlas:hive-bridge:jar:3.0.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.hive:hive-standalone-metastore:jar:3.1.0, org.apache.derby:derby:jar:10.14.1.0, co.cask.tephra:tephra-core:jar:0.6.0, com.google.inject:guice:jar:3.0, it.unimi.dsi:fastutil:jar:6.5.6, org.apache.hive:hive-service:jar:3.1.0: Could not transfer artifact org.apache.hive:hive-standalone-metastore:jar:3.1.0 from/to central (https://repo1.maven.org/maven2): GET request of: org/apache/hive/hive-standalone-metastore/3.1.0/hive-standalone-metastore-3.1.0.jar from central failed: No space left on device -> [Help 1]
#0 559.0 [ERROR] 
#0 559.0 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#0 559.0 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#0 559.0 [ERROR] 
#0 559.0 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#0 559.0 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
#0 559.0 [ERROR] 
#0 559.0 [ERROR] After correcting the problems, you can resume the build with the command
#0 559.0 [ERROR]   mvn <goals> -rf :hive-bridge

**Comment by lucasmsp** [comment]
Hi @davidpr, it seems that this error is related to the message "No space left on device". While building the containers, make sure to have enough free space on your partition.

**Comment by davidpr** [comment]
Hi @lucasmsp, it's strange because although I'm using Docker desktop on mac (Intel) I have 120GB of disk left and 64GB reserved for the docker desktop virtualization. I'll investigate if there's some other limitation I'm not seeing.
