### ISSUE TITLE
Atlas waiting to be ready

### ISSUE THREAD

**Issue by davidpr** [lucasmsp/docker-atlas#4]
Hi, if I execute the docker-compose up in an Ubuntu, the process gets stuck in the point of "waiting for atlas to be ready" for more than 30' and then stuck again in the last line:

kafka                        | [2022-12-07 06:18:15,827] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-43 in 70 milliseconds for epoch 0, of which 70 milliseconds was spent in the scheduler. (kafka.coordinator.group.GroupMetadataManager)
kafka                        | [2022-12-07 06:18:15,828] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-13 in 71 milliseconds for epoch 0, of which 71 milliseconds was spent in the scheduler. (kafka.coordinator.group.GroupMetadataManager)
kafka                        | [2022-12-07 06:18:15,828] INFO [GroupMetadataManager brokerId=1001] Finished loading offsets and group metadata from __consumer_offsets-28 in 72 milliseconds for epoch 0, of which 72 milliseconds was spent in the scheduler. (kafka.coordinator.group.GroupMetadataManager)
kafka                        | [2022-12-07 06:18:15,899] INFO [GroupCoordinator 1001]: Dynamic Member with unknown member id joins group atlas in Empty state. Created a new member id consumer-1-b91b82b5-e00c-44f1-8c25-47fd2a444db3 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 06:18:15,931] INFO [GroupCoordinator 1001]: Preparing to rebalance group atlas in state PreparingRebalance with old generation 0 (__consumer_offsets-3) (reason: Adding new member consumer-1-b91b82b5-e00c-44f1-8c25-47fd2a444db3 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 06:18:15,968] INFO [GroupCoordinator 1001]: Stabilized group atlas generation 1 (__consumer_offsets-3) with 1 members (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 06:18:16,006] INFO [GroupCoordinator 1001]: Assignment received from leader for group atlas for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
atlas-server_1               | waiting for atlas to be ready

zookeeper_1                  | 2022-12-07 07:06:59,840 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@138] - Purge task started.
zookeeper_1                  | 2022-12-07 07:06:59,841 [myid:] - INFO  [PurgeTask:DatadirCleanupManager$PurgeTask@144] - Purge task completed.
datanode_1                   | 22/12/07 07:26:58 INFO datanode.DirectoryScanner: BlockPool BP-1202119258-172.19.0.4-1670393223844 Total blocks: 0, missing metadata files:0, missing block files:0, missing blocks in memory:0, mismatched blocks:0

I'm using this Docker:
docker version
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:58 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by lucasmsp** [comment]
Hi, this docker-compose project involves many big data tools (Atlas, Zoo, Kafka, HDFS, Hive and Spark). If you don't have enough resources, it will take some time to fully initialize. While Atlas depends on Zookeeper and Kafka, the others are optional. If you dont need them, comment on them in yml file. 

I'm closing this issue, but be free to reopen it.

**Comment by davidpr** [comment]
Just running the command again has solved the issue:

...
hive-metastore_1             | 2022-12-07T10:17:11,334 INFO [pool-7-thread-2] org.apache.hadoop.hive.metastore.HiveMetaStore - 1: source:172.19.0.9 get_multi_table : db=default tbls=
zookeeper_1                  | 2022-12-07 10:17:30,142 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@215] - Accepted socket connection from /172.19.0.8:52634
zookeeper_1                  | 2022-12-07 10:17:30,143 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@949] - Client attempting to establish new session at /172.19.0.8:52634
zookeeper_1                  | 2022-12-07 10:17:30,146 [myid:] - INFO  [SyncThread:0:ZooKeeperServer@694] - Established session 0x100035f0dbf0004 with negotiated timeout 20000 for client /172.19.0.8:52634
kafka                        | [2022-12-07 10:17:33,808] INFO [GroupCoordinator 1001]: Dynamic Member with unknown member id joins group atlas in Empty state. Created a new member id consumer-1-9a8ba1f5-19cf-4761-be0a-a2493f8dd3b9 for this member and add to the group. (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 10:17:33,812] INFO [GroupCoordinator 1001]: Preparing to rebalance group atlas in state PreparingRebalance with old generation 2 (__consumer_offsets-3) (reason: Adding new member consumer-1-9a8ba1f5-19cf-4761-be0a-a2493f8dd3b9 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 10:17:33,840] INFO [GroupCoordinator 1001]: Stabilized group atlas generation 3 (__consumer_offsets-3) with 1 members (kafka.coordinator.group.GroupCoordinator)
kafka                        | [2022-12-07 10:17:33,881] INFO [GroupCoordinator 1001]: Assignment received from leader for group atlas for generation 3. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
atlas-server_1               | ...........................................
atlas-server_1               | Apache Atlas Server started!!!
atlas-server_1               |
