### ISSUE TITLE
How to integrate data using kafka?

### ISSUE THREAD

**Issue by phanducquang** [lucasmsp/docker-atlas#7]
I am looking for a solution using Kafka to integrate new data into Apache Atlas. Please tell me how to connect to Kafka.
Thank you very much,

**Comment by lucasmsp** [comment]
Hi, I suggest checking out this [page](https://atlas.apache.org/2.0.0/Bridge-Kafka.html). It explains how to install Kafka's hook to register its operations in Atlas.
