### ISSUE TITLE
Apache Atlas Storm Bridge Shim Failure

### ISSUE THREAD

**Issue by HorusIXI** [lucasmsp/docker-atlas#9]
Hi, im trying to build this docker project, but i get an error trying to build storm bridge shim.

[INFO] Apache Atlas Falcon Bridge ......................... SUCCESS [  2.273 s]
[INFO] Apache Atlas Sqoop Bridge Shim ..................... SUCCESS [  2.767 s]
[INFO] Apache Atlas Sqoop Bridge .......................... SUCCESS [ 11.434 s]
[INFO] Apache Atlas Storm Bridge Shim ..................... FAILURE [  7.402 s]
[INFO] Apache Atlas Storm Bridge .......................... SKIPPED
[INFO] Apache Atlas Hbase Bridge Shim ..................... SKIPPED
[INFO] Apache Atlas Hbase Bridge .......................... SKIPPED
[INFO] Apache HBase - Testing Util ........................ SKIPPED
[INFO] Apache Atlas Kafka Bridge .......................... SKIPPED
[INFO] Apache Atlas classification updater ................ SKIPPED
[INFO] Apache Atlas Impala Hook API ....................... SKIPPED
[INFO] Apache Atlas Impala Bridge Shim .................... SKIPPED
[INFO] Apache Atlas Impala Bridge ......................... SKIPPED
[INFO] Apache Atlas Distribution 3.0.0-SNAPSHOT ........... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project storm-bridge-shim: Error resolving project artifact: Failure to transfer ring-cors:ring-cors:pom:0.1.5 from https://maven.java.net/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of java.net-Public has elapsed or updates are forced. Original error: Could not transfer artifact ring-cors:ring-cors:pom:0.1.5 from/to java.net-Public (https://maven.java.net/content/groups/public/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target for project ring-cors:ring-cors:jar:0.1.5 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :storm-bridge-shim
ERROR: Service 'atlas-server' failed to build: The command '/bin/sh -c git clone http://github.com/apache/atlas.git     && cd atlas     && git reset --hard $ATLAS_REV      && mvn clean -DskipTests package -Pdist,embedded-hbase-solr     && mv distro/target/apache-atlas-*-bin.tar.gz /apache-atlas.tar.gz' returned a non-zero code: 1

Do you know how to solve this problem?

**Comment by lucasmsp** [comment]
Fixed in #14
